name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04  # Switch to Ubuntu 22.04

    strategy:
      matrix:
        python-version: [3.8, 3.10, 3.12]  # Stick with supported versions

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format code
      run: make format

    - name: Lint code
      run: make lint

    - name: Run tests
      run: make test
